### ISSUE TITLE
Function get_taxa()

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#1]
```r
get_taxa <- function(
    taxon_keys = NULL
    checklist_keys = NULL
    limit = NULL
)
```

## Parameters

If parameter `taxon_keys`:

* [ ] Allows single taxon key (an integer)
* [ ] Allows vector of taxon keys (vector of integers)
* [ ] Functionality: use function`name_usage()` to query e.g. http://api.gbif.org/v1/species/5231190
* [ ] If used together with `checklist_keys`: assertion error

If parameter `checklist_keys`:

* [ ] Works with single dataset key (a string)
* [ ] Works with vector of datasets keys (vector of strings)
* [ ] Functionality: use function `name_usage(datasetKey = ...)`
* [ ] If used together with `taxon_keys`: assertion error

If parameter `limit` (e.g. 10)

* [ ] With `taxon_keys`: limit to 10 taxa
* [ ] With `checklist_keys`: limit to 10 taxa **PER DATASET**

## Return

* [ ] A dataframe with **all returned attributes** for any taxa:

key | nubKey | nameKey | taxonID | sourceTaxonKey | kingdom | ...
--- | --- | --- | --- | --- | --- | ---
134087746 | 5567657 | 15913604 | 2346 | NA | Plantae | ...
5567657 | 5567657 | 1439808 | gbif:5567657 | 123978664 | Plantae | ...

* [ ] Columns can be in any order, but `key` (= input taxonKey) should be first.
* [ ] Don't return metadata such as `limit`, `offset`

## Warning

* [ ] If taxonKey not found by `nameUsage()`: store in vector. At end of retrieving all keys, add those to the returned dataframe, with column `key` populated and all other columns NA. Also provide warning message, listing the keys that were not found at GBIF. Note: this should never happen with parameter `checklist_keys`. 😄 

This function should replace:

* [ ] checklist_import()
* [ ] checklists_import()

## Documentation

* [ ] Document all above as succinct as possible with roxygen

**Comment by damianooldoni** [comment]
> with single taxon key (a string)
Works with vector of taxon keys (vector of strings)

Are taxon keys `character`? I always used them as `numeric`.

**Comment by peterdesmet** [comment]
You're right, will update body of this issue.

**Comment by peterdesmet** [comment]
You're right. However, taxon keys might come from data file where they are defined as character. But OK, let's force user to cast them to integer before passing to function. I'll update issue body.

**Comment by damianooldoni** [comment]
As discussed, contrarily to documentation, rgbif allows the usage of key as character.
`name_usage(key = 1)` and `name_usage(key = "1")` give the same output.
Based on this, I will update my get_taxa function as well.

**Comment by damianooldoni** [comment]
`get_taxa` is ready for hard testing, @peterdesmet!

**Comment by damianooldoni** [comment]
I cleaned the branch [implement-paging&get-taxa-steps](https://github.com/trias-project/trias/tree/implement-paging%26get-taxa-steps) of trias package. Now only get_taxa function is visible. Test directory has also been cleaned up with just tests related to `get_taxa` function.
Package reinstalled and succesfully tested. 
@peterdesmet: check it please one last time. Thanks!

**Comment by peterdesmet** [comment]
Will do. Note: always good to add a link to the PR: https://github.com/trias-project/trias/pull/3... but well, it's a bit confusing anyway that we made this issues in this repository rather than `trias`. 😄

**Comment by damianooldoni** [comment]
I think we should close this issue because:

1. Function has been implemented, documented and tested. See [trias::gbif_get_taxa()](https://github.com/trias-project/trias/blob/master/R/gbif_get_taxa.R).
2. We don't use it anymore actually :rofl:

**Comment by peterdesmet** [comment]
Agreed. If you want to clean up things and remove the function, then you should probably create an issue to do that. 😉
