### ISSUE TITLE
Expected output of verify_taxa.Rmd

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#14]
File named `taxa_after_verification.csv`

- [ ] key: same as in `taxa.csv`
- [ ] scientificName: same as in `taxa.csv`
- [ ] taxonID: same as in `taxa.csv`
- [ ] datasetKey: same as in `taxa.csv`
- [ ] ~~nameType: same as in `taxa.csv`~~
- [ ] ~~issues: same as in `taxa.csv`~~
- [ ] validDistribution: same as in `taxa.csv`
- [ ] verifiedKey: same as in `taxa.csv`
- [ ] bb_key = trias_verifiedKey
- [ ] bb_scientificName: regarding `trias_verifiedKey`
- [ ] bb_species: regarding `trias_verifiedKey`
- [ ] bb_genus: regarding `trias_verifiedKey`
- [ ] bb_family: regarding `trias_verifiedKey`
- [ ] bb_order: regarding `trias_verifiedKey`
- [ ] bb_class: regarding `trias_verifiedKey`
- [ ] bb_phylum: regarding `trias_verifiedKey`
- [ ] bb_kingdom: regarding `trias_verifiedKey`
- [ ] bb_rank: regarding `trias_verifiedKey`
- [ ] bb_speciesKey: regarding `trias_verifiedKey`
- [ ] bb_taxonomicStatus: regarding `trias_verifiedKey`
- [ ] ~~bb_acceptedKey: regarding `trias_verifiedKey`~~
- [ ] ~~bb_acceptedName: regarding `trias_verifiedKey`~~

Note that `trias_verifiedKey` should only contain a single value. Taxa that are verified to multiple taxa should thus appear as multiple lines

**Comment by damianooldoni** [comment]
yes, modifying function `trias::verify_taxa.R` is in my to-do-list.

**Comment by damianooldoni** [comment]
While screening issues where I am involved, I found this old one. Is this solved? I think so.

**Comment by peterdesmet** [comment]
Yes, the whole verify_taxa step has been handled.
