### ISSUE TITLE
Format for sources

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#24]
### taxonRemarks for taxa

Lists the datasets considered for unifying information:

> Sources considered for unifying information: https://DOI, https://DOI, https://DOI

Note: this is not the source for the taxon information (that would be GBIF Backbone taxonomy), but just extra information (hence why we put it in `taxonRemarks`)

Todo:

- [x] `dwc_mapping.Rmd`: add correct taxonRemarks format to taxa

### Source for distribution, species profile, description

Includes the link to the specific checklist taxon that was used for this piece of information:

> https://www.gbif.org/species/141264581: Nymphaea marliacea Marliac in Verloove F, Groom Q, Brosens D, Desmet P, Reyserhove L (2018). Manual of the Alien Plants of Belgium. Version 1.7. Botanic Garden Meise. Checklist dataset https://doi.org/10.15468/wtda1m

Todo:

- [x] `get_taxa.Rmd`: Remove "accessed via GBIF.org on xxxx-xx-xx." from citation and add as `citation` to `checklists.csv`
- [x] `unify_information.Rmd`: add `sourceScientificName` to distribution
- [x] `unify_information.Rmd`: add `sourceScientificName` to species profile
- [x] `unify_information.Rmd`: add `sourceScientificName` to description
- [x] `dwc_mapping.Rmd`: create small `build_source_citation()` function, taking the arguments `taxonKey`, `scientificName`, `datasetCitation`
- [x] `dwc_mapping.Rmd`: add correct source format to distribution
- [x] `dwc_mapping.Rmd`: add correct source format to species profile
- [x] `dwc_mapping.Rmd`: add correct source format to description

**Comment by LienReyserhove** [comment]
I already added the scientific names to distribution and species profile. However, not really sure what to do with the description here, as there is no taxonKey to link the scientific name to.
I see that this is the consequnce of using `distinct()` here. I guess there's no way to link the scientificName to verificationKey, as we will harverst the accepted name from gbif then, right?
Suggestions to use something different than `distinct()` in order to keep the taxonKey?

**Comment by peterdesmet** [comment]
Function created to add source:

https://github.com/trias-project/unified-checklist/blob/4b7605e0b5bf2c1a8a2f9a4e3e737c6a51818ff0/src/6_dwc_mapping.Rmd#L132-L135

All the rest is done, closing issue.
