### ISSUE TITLE
remove native birds from unified checklist

### ISSUE THREAD

**Issue by timadriaens** [trias-project/unified-checklist#32]
while checking the birds extract from the unified there appear to be a number of species native to Belgium on the unified checklist

| __Species__ | __Argumentation__ |
| ------------- |------------ |
| Perdix perdix (Linnaeus, 1758) | native red list species but indeed restocking occurs regularly for hunting |
| Dryocopus martius (Linnaeus, 1758) | native black woodpecker |
| Bubulcus ibis (Linnaeus, 1758) | vagrant, more and more seen, also kept in aviaries |
| Nycticorax nycticorax (Linnaeus, 1758) | native breeding heron species, but also kept in aviaries |
| Ciconia nigra (Linnaeus, 1758) | native black stork, rare breeder |
| Emberiza hortulana Linnaeus, 1758 | probably also kept in aviaries but would take it out, rare vagrant |
| Tarsiger cyanurus (Pallas, 1773) | rare vagrant |
| Athene noctua (Scopoli, 1769) | native little owl |
| Anser fabalis (Latham, 1787) | winter migrant, possibly also bred in waterfowl collections |
| Anser anser (Linnaeus, 1758) | mixed population of wild and escaped birds but native to Belgium |
| Milvus migrans (Boddaert, 1783) | native |
| Bubo bubo (Linnaeus, 1758) | native, breeding, but kept widely in collections |
| Branta leucopsis (Bechstein, 1803) | native, breeding, wintering, mixed population of wild and birds of escaped origin |

these would imo best be taken out of the unified for now @LienReyserhove .

**Comment by LienReyserhove** [comment]
It would be good to have an column included here with the reference to the source checklist. I included this in the [extract of the unified checklist](https://docs.google.com/spreadsheets/d/1ugsmAq_tlUjFmZef2zyw-mT0Tq1jSdPlNO4KTfJyXVo/edit#gid=859388866)  (field `source` in the spreadsheet)

**Comment by peterdesmet** [comment]
@timadriaens the species you list are no longer included since we removed RINSE https://doi.org/10.15468/focajn, except for:

- Anser fabalis, which is included in RINSE pathways (https://doi.org/10.15468/guejza)
- Anser anser, which is included in RINSE pathways (https://doi.org/10.15468/guejza)
- Branta leucopsis, which is included in RINSE pathways (https://doi.org/10.15468/guejza)

The only we can remove those is by specifically excluding them in our processing

**Comment by peterdesmet** [comment]
Updated the spreadsheet @LienReyserhove created. The remaining birds are:

```
Tadorna ferruginea (Pallas, 1764)
Anser fabalis (Latham, 1787)
Anser indicus (Latham, 1790)
Anser anser (Linnaeus, 1758)
Anas falcata Georgi, 1775
Anas sibilatrix Poeppig, 1829
Anas americana (Gmelin, 1789)
Alopochen aegyptiaca (Linnaeus, 1766)
Oxyura jamaicensis (Gmelin, 1789)
Cygnus atratus (Latham, 1790)
Aix sponsa Linnaeus, 1758
Aix galericulata (Linnaeus, 1758)
Marmaronetta angustirostris (MÃ©nÃ©triÃ©s, 1832)
Chloephaga picta (Gmelin, 1789)
Branta canadensis (Linnaeus, 1758)
Branta leucopsis (Bechstein, 1803)
```

**Comment by timadriaens** [comment]
All of these are non-native, except for these goose species for the reasons outlined above. Question @peterdesmet : would it not make more sense to remove them from the source checklist on which they apparently occur (because this is a mistake in the source checklist...)? And second: shouldn't we publish the alien bird checklist and give this one priority over the other bird related sources perhaps this will solve this problem?

Anser fabalis (Latham, 1787)
Anser anser (Linnaeus, 1758)
Branta leucopsis (Bechstein, 1803)

**Comment by peterdesmet** [comment]
Removing from source checklist: yes, we could remove those distributions there, but then it will differ from what was included as supplementary material to the paper.

Bird checklist should get higher priority, but since they won’t be included there, they will still pop up from rinse pathways.

**Comment by timadriaens** [comment]
Clearly the supplementary material to this paper contains mistakes (also for the UK as one reviewer of that paper pointed out to me). For me, this shows that expert check is missing as a step in the pipeline to the unified. @peterdesmet @damianooldoni any ideas on how to tackle this issue of mistakes in the source checklists? Maybe, instead of prioritizing at checklist level, we should prioritize at [checklist + taxon] level i.e. we discard the birds from the RINSE pathway checklist and include the bird checklist? But then again, such decision for me needs to be based on expert review first.

**Comment by LienReyserhove** [comment]
I agree with @timadriaens that we should first get the list reviewed by experts, before we start prioritizing lists in the pipeline. We now have the checklist published, the next step is to get it reviewed.

**Comment by timadriaens** [comment]
I realize this is probably not feasible within the TrIAS project and we have other priorities now, but at least such gaps should be pointed out/documented/published.

**Comment by mcoupremanne** [comment]
Hi all,
This might be an out-dated 2 cents contribution but at DEMNA I was also questionned about the presence of Ancer Ancer , Brenta leucopsis (protected) and Podarcis muralis (protected, N2000) in the unified checklist.

2 more cents :  Before the unified checklist was up, I used the different source checklists to target our exotic taxa. Some native (eg. Astacus astacus) were listed in the RINSE checklist, before we target only exotics for belgium by joining the distribution table. Just to let you know this issue even if I guess it was taken into account in the unified checklist.
Very best regards,
Maxime.

**Comment by timadriaens** [comment]
@mcoupremanne Podarcis muralis is there because it is non-native to Flanders (introduced with habitat material probably and still spreading along the railway network). We should indeed decide what to do with such cases, because it is strange they appear on a belgian alien species checklist. Anser anser and Branta leucopsis: see above, they are mixed populations of wild and escaped birds, we decided to rule them out of our definition of 'true aliens'.

**Comment by timadriaens** [comment]
Upon working with the unified checklist, these issues still needs to be tackled. The 3 geese should be off the unified in one way or another. We decided that we would not include them on the bird checklist, so for consistency using the same argument they should also be taken out of the other cheklists that have them (RINSE and RINSE pathways). I feel there is nothing wrong to make such decisions at source checklist level and it can all be mentioned in the metadata to the source checklists. @peterdesmet @LienReyserhove any thoughts?

**Comment by peterdesmet** [comment]
We can include a step to exclude certain species 👍 That would be these ones:

Anser fabalis (Latham, 1787)
Anser anser (Linnaeus, 1758)
Branta leucopsis (Bechstein, 1803)

?

**Comment by timadriaens** [comment]
yep

**Comment by peterdesmet** [comment]
This is now fixed in the pipeline and repo data, but I don't really see a need to republish it to GBIF just for that.

**Comment by damianooldoni** [comment]
I should then remove them from preprocessing pipelines of indicators. Otherwise I get them, e.g. 
in the spread of alien species in Flemish habitat directive areas (as asked from @timadriaens): https://trias-project.github.io/indicators/status_alien_species_in_protected_areas.html#532_flanders
