### ISSUE TITLE
How to add more WRIMS distributions

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#37]
WRIMS distributions need a combination of:

```
"country": "BE",
"status": "PRESENT"
"establishmentMeans": "INTRODUCED",
```

... to be selected. Ideally they have temporal information:

```
"temporal": "2000",
```

I notice many distributions only have part of the information: e.g. year, but not status. Search for example for `"BE"` in https://api.gbif.org/v1/species/157131005/distributions: there are 8 distributions for Belgium, but none have all 3 properties _and_ year.

I wonder if we should drop the `status` field in our selection.

**Comment by peterdesmet** [comment]
Dropping filter on status `present` adds 2592 -> 2638 = 46 new taxa overall

**Comment by qgroom** [comment]
Or perhaps NOT ABSENT would be more future proof.

**Comment by peterdesmet** [comment]
Brilliant!! Requires an update of the `gbif_has_distribution()` function, so cannot test right away. Would you also excluded distributions that are defined as `DOUBTFUL`?

**Comment by qgroom** [comment]
Yes, ignore `DOUBTFUL`

**Comment by peterdesmet** [comment]
Implemented in #39. It's an improvement overall, the only negative effect is that two distributions now lost their years (they had it in RINSE pathways, but not in WRIMS and WRIMS takes precedence).

**Comment by peterdesmet** [comment]
From https://github.com/trias-project/wrims-checklist/issues/2#issuecomment-483296534, these are the values WRIMS has for:

## occurrenceStatus

WRiMS value | [interpretation by GBIF](https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/occurrence_status.tsv) | [in unified](https://github.com/trias-project/unified-checklist/blob/master/src/1_get_taxa.Rmd#L159-L163)
--- | --- | ---
Absent | ABSENT | excluded by filter 👍
Detected in invasion pathway | - | included 👍
Detected in the wild | - | included 👍
doubtful | DOUBTFUL | excluded by filter 👍
**Eradicated** | - | should be excluded 👎, but no records for Belgium 👍
Established | - | included 👍
Established and expanding | - | included 👍
Established and stable | - | included 👍
excluded | EXCLUDED | excluded by filter 👍
In captivity/cultivated | - | included 👍
**Not specified** | - | should be excluded 👎, but no records for Belgium 👍
present | PRESENT | included 👍
**Recorded in error** | - | should be excluded 👎, but no records for Belgium 👍
**Reported** | EXCLUDED | excluded by filter 👎, should be updated at GBIF
Sometimes present | - | included 👍
**Uncertain** | - | should be excluded 👎

## establishmentMeans

WRIMS value | [GBIF interpretation](https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/establishment_means.tsv) | [in unified](https://github.com/trias-project/unified-checklist/blob/master/src/1_get_taxa.Rmd#L159-L163)
--- | --- | ---
Origin unknown | UNCERTAIN | not included 👍 
Origin uncertain | UNCERTAIN | not included 👍
Alien | INTRODUCED | included 👍
Native | NATIVE | not included 👍
**Native Endemic** | - | not included 👍
**Native Non-endemic** | - | not included 👍

**Comment by peterdesmet** [comment]
So most of it good, but will report the bold ones to GBIF for better mapping.

**Comment by peterdesmet** [comment]
@qgroom, are there any other values in https://github.com/trias-project/unified-checklist/issues/37#issuecomment-493006247 that you would map to GBIF vocab (those with a `-` in column 2)? E.g.:

```
Eradicated -> ABSENT ?
Established -> ??
```

If so, I will report them to GBIF

**Comment by qgroom** [comment]
I'm not total clear on the question, but here is my response anyway...

detected in wild -> PRESENT
Established  -> PRESENT
Established and expanding -> PRESENT
Established and stable -> PRESENT

Sometimes present -> IRREGULAR

In captivity/cultivated -> dwc:degreeOfEstablishment category B

**Comment by peterdesmet** [comment]
https://github.com/gbif/parsers/issues/15 is now resolved, so taxa that are "reported" are now longer excluded. Will rerun pipeline.

@qgroom, your suggestions seem ok, but less important to report to GBIF as they don't effect the pipeline.

**Comment by peterdesmet** [comment]
Done in https://github.com/trias-project/unified-checklist/commit/7384c21544f80dfbff6d5f01f38ed995227b47f3: 4 taxa added
