### ISSUE TITLE
Symphoricarpos albus (L.) S.F.Blake missing from unified checklist

### ISSUE THREAD

**Issue by qgroom** [trias-project/unified-checklist#40]
Symphoricarpos albus (L.) S.F.Blake is in the Alien Plants of Belgium checklist, but is missing from the unified checklist.

Alien Plants of Belgium checklist
https://www.gbif.org/species/141267078

Perhaps this is something to do with the synonymy, but I can't see an obvious problem.

**Comment by peterdesmet** [comment]
It hasn’t been verified:

https://github.com/trias-project/unified-checklist/blob/e0b2d5fe13076cf54091985fd3fe6b68e141010d/references/verification.tsv#L523

Lots of plants miss verification in the spreadsheet. A task for Filip?

**Comment by qgroom** [comment]
Ah! I had assumed that we were including the unverified species, because they are already "verified" being included on the checklist. It is a bit unclear what exactly we are verifying, I thought it was the synonymy, rather than the presence in the country. I will probably have to find some time to do this myself.

**Comment by peterdesmet** [comment]
It is (only) synonymy 😄 :

Symphoricarpos albus (L.) S.F. Blake ->Symphoricarpos albus (L.) C.Koch

HETEROTYPIC_SYNONYM and change in author.

**Comment by qgroom** [comment]
I've updated the spreadsheet for Symphoricarpos albus. No reason to keep this issue open, I know what is needed to be done.

**Comment by peterdesmet** [comment]
Now included in checklist (but not yet republished on GBIF)
