### ISSUE TITLE
Include distribution for regions

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#43]
As discussed in https://github.com/inbo/natuurindicatoren/issues/14#issuecomment-505932765 and for feeding the Harmonia website, it would be good to also unify distributions for the regions (when that information is available in the source checklist).

**Comment by damianooldoni** [comment]
In checklists merged to the unified checklist, we have more than the standard three regions:. Still, I would limit distributions at regional level only, without mentioning cities or other kind of localities. @peterdesmet : do you agree with the mapping here below? This mapping obviously has nothing to do and will not affect the distributions at national level. I would save this kind of table as a reference file in `./references/locality_mapping.tsv`;

locality | locationId | locality_assigned | locationID_assigned
-- | -- | -- | --
Belgium | ISO_3166-2:BE | Belgium | ISO_3166-2:BE
Flemish Region | ISO_3166-2:BE-VLG | Flemish Region | ISO_3166-2:BE-VLG
Brussels-Capital Region | ISO_3166-2:BE-BRU | Brussels-Capital Region | ISO_3166-2:BE-BRU
Walloon Region | ISO_3166-2:BE-WAL | Walloon Region | ISO_3166-2:BE-WAL
Belgian part of the North Sea | http://marineregions.org/mrgid/26567 | Belgium | ISO_3166-2:BE
Belgian Exclusive Economic Zone | http://marineregions.org/mrgid/3293 | Belgium | ISO_3166-2:BE
Spuikom | http://marineregions.org/mrgid/5477 | Flemish Region | ISO_3166-2:BE-VLG
Oostende Harbour | http://marineregions.org/mrgid/5476 | Flemish Region | ISO_3166-2:BE-VLG
Nieuwpoort Harbour | http://marineregions.org/mrgid/5479 | Flemish Region | ISO_3166-2:BE-VLG
port of Bruges-Zeebrugge | http://marineregions.org/mrgid/19669 | Flemish Region | ISO_3166-2:BE-VLG
Zeebrugge | http://marineregions.org/mrgid/2551 | Flemish Region | ISO_3166-2:BE-VLG
Oostende | http://marineregions.org/mrgid/65 | Flemish Region | ISO_3166-2:BE-VLG
Koksijde | http://marineregions.org/mrgid/91 | Flemish Region | ISO_3166-2:BE-VLG
Baai van Heist | http://marineregions.org/mrgid/19674 | Flemish Region | ISO_3166-2:BE-VLG
Blankenberge Harbour | http://marineregions.org/mrgid/5478 | Flemish Region | ISO_3166-2:BE-VLG
Bredene | http://marineregions.org/mrgid/66 | Flemish Region | ISO_3166-2:BE-VLG
De Panne | http://marineregions.org/mrgid/92 | Flemish Region | ISO_3166-2:BE-VLG
Belgian Coast | http://marineregions.org/mrgid/2550 | Flemish Region | ISO_3166-2:BE-VLG
Haven van Antwerpen | http://marineregions.org/mrgid/5481 | Flemish Region | ISO_3166-2:BE-VLG
Kanaal Gent - Terneuzen | http://marineregions.org/mrgid/21706 | Flemish Region | ISO_3166-2:BE-VLG
Port of Ghent | http://marineregions.org/mrgid/30743 | Flemish Region | ISO_3166-2:BE-VLG
Knokke-Heist | http://marineregions.org/mrgid/37 | Flemish Region | ISO_3166-2:BE-VLG
Oostende | http://marineregions.org/mrgid/25 | Flemish Region | ISO_3166-2:BE-VLG
Coastal Polders | http://marineregions.org/mrgid/2536 | Flemish Region | ISO_3166-2:BE-VLG

**Comment by peterdesmet** [comment]
Regional distributions were implemented in #18
