### ISSUE TITLE
"Natural" is not a level 1 CBD pathway category

### ISSUE THREAD

**Issue by SanderDevisscher** [trias-project/unified-checklist#48]
upon updating the biodiversity indicators for Flanders with @SanderDevisscher we noticed "natural" has become a category at level 1. Therefore, the indicator table on pathways also gives a number of species for unaided and for natural dispersal separately which is no good (they are synonymous). See the vocab table for [pathways](https://github.com/trias-project/vocab/blob/master/vocabulary/pathway/pathways.tsv), here line 52 is in fact redundant because if level 1 is unaided then level 2 is always natural dispersal.

In fact, "unaided" (level 1) is the same as "natural dispersal" (level 2). 
So probably something happens in the function which results in this.

**Comment by damianooldoni** [comment]
Thanks @SanderDevisscher to notice this!
However, this is a bug in code of preprocessing data for pathway indicators, not for unified checklist.
See open issue in indicators repo: https://github.com/trias-project/indicators/issues/61.
I close this one.
