### ISSUE TITLE
quality control GRIIS Belgium - fish

### ISSUE THREAD

**Issue by timadriaens** [trias-project/unified-checklist#64]
Whilst scanning through the list of species selected for the MijnVismaat occurrences dataset, noticed a few native species in there. I suspect this has to do with using GRIIS Belgium as a selection filter and indeed, those species appear to be on GRIIS Belgium:

- [ ] Silurus glanis (GBIF key 2337607): although it is true that the current population of this species is the result of (re)introductions, there is historic proof it is a native species so should have degree of establishment nativeReintroduced
- [ ] Leuciscus idus (GBIF key 4409643): simply native

These species do not belong on the alien species checklist for Belgium. They originate from the [Zieritz et al. checklist](https://www.gbif.org/dataset/1738f272-6b5d-4f43-9a92-453a8c5ea50a).

**Comment by timadriaens** [comment]
therefore, I have sent the list again to @HugoVerreycken who checked the column "established in Belgium" again. As there are clearly mistakes in there, I propose to simply adjust the original source and make note of that in the metadata. We can justify this stating that one of the authors of the paper did this. Otherwise it will  be cumbersome to take them out of GRIIS probably? Let me know how you feel about that @peterdesmet

**Comment by timadriaens** [comment]
I am giving the overview of the adaptations that should be made here:

- [ ] Ameiurus melas: does not occur in Belgium, only A. nebulosus
- [ ] Clarias gariepinus: not established but casual 
- [ ] Ctenopharyngodon idella: not established but casual 
- [ ] Hucho hucho: never reported in Belgium
- [ ] Hypophthalmichthys molitrix: not established but casual
- [ ] Hypophthalmichthys nobilis: not established but casual
- [ ] Ictalurus punctatus: not established but casual
- [ ] Leucaspius delineatus: native
- [ ] Leucaspius delineatus: native
- [ ] Leuciscus idus: native
- [ ] Oncorhynchus kisutch: not established, maybe casual in Wallonia
- [ ] Oncorhynchus mykiss: not established but casual
- [ ] Oreochromis niloticus: not established but casual
- [ ] Salvelinus frontalis: not established in Belgium, only reported in Wallonia not in Flanders
- [ ] Silurus glanis: native but reintroduced so should have degree of establishment nativeReintroduced
- [ ] Vimba vimba: never reported in Belgium

**Comment by sannegovaert** [comment]
Follow up, as it is now on the freshwater fishes checklist:

Species | remark Tim | freshwater fishes checlist 2024  | check 2024
-- | --- | ---- | -----
 Ameiurus melas | does not occur in Belgium, only A. nebulosus | established  | [ ]
 Clarias gariepinus |  not established but casual | cultivated | [ ]
 Ctenopharyngodon idella | not established but casual | casual | [ ]
 Hucho hucho  | never reported in Belgium | not on the list | [ ]
 Hypophthalmichthys molitrix  | not established but casual | 
 Hypophthalmichthys nobilis  | not established but casual | 
 Ictalurus punctatus: not established but casual | casual | [ ]
 Leucaspius delineatus | native | not on the list | [ ]
 Leuciscus idus |  native | not on the list | [ ]
 Oncorhynchus kisutch |  not established, maybe casual in Wallonia | not on the list | [ ]
 Oncorhynchus mykiss |  not established but casual | casual | [ ]
 Oreochromis niloticus | not established but casual | cultivated | [ ]
 Salvelinus frontalis |  not established in Belgium, only reported in Wallonia not in Flanders | not on the list | [ ]
 Silurus glanis |  native but reintroduced so should have degree of establishment nativeReintroduced | not on the list | [ ]
 Vimba vimba |  never reported in Belgium | casual (observed in 2020) | [ ]
 
 I checked the box if the remarks from 2020 and the current list are the same.
  @timadriaens Can you check the differences?

**Comment by qgroom** [comment]
From the point of view of the dwc:degreeOfEstablishment vocabulary I wonder whether the ones marked as casual should be categorized as `released (category B3)` http://rs.tdwg.org/dwcdoe/values/d004

The difference being that these fish have been actively released, but are not reproducing.

**Comment by timadriaens** [comment]
Good point indeed. We stayed close to the vocab of Hugo's first paper but since we have the new terms we should map them again. We have a meeting with the fish guys on the 25th and shall ask them to do that.

**Comment by sannegovaert** [comment]
We discussed all of this during a meeting and take it into account, so I close this issue.
