### ISSUE TITLE
Taxa with extensions information missing in taxon core

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/unified-checklist#67]
I found three taxa in speciesProfiles which are missing in the taxon core.

```r
> speciesProfiles %>% anti_join(taxon, by = "id")
anti_join: added no columns
           > rows only in x       3
           > rows only in y  (   37)
           > matched rows    (2,999)
           >                 =======
           > rows total           3
# A tibble: 3 x 7
  id        is_marine is_freshwater is_terrestrial is_invasive habitat  source       
  <chr>     <lgl>     <lgl>         <lgl>          <lgl>       <chr>    <chr>        
1 https://~ FALSE     TRUE          TRUE           NA          freshwa~ https://www.~
2 https://~ FALSE     TRUE          TRUE           NA          freshwa~ https://www.~
3 https://~ FALSE     TRUE          TRUE           NA          freshwa~ https://www.~
```

`id` of these three taxa:
- https://www.gbif.org/species/2498027
- https://www.gbif.org/species/2498036
- https://www.gbif.org/species/5232464

I think the origin of this bug is in this section of the workflow:
https://trias-project.github.io/unified-checklist/4_unify_taxa.html#explicitely-remove-incorrect-taxa

We remove these taxa from the taxon core but not from the extension.

**Comment by damianooldoni** [comment]
@peterdesmet: I think you solved this issue as I don't found any species profile information for these species in the unified. Am I right?

**Comment by peterdesmet** [comment]
I can't recall if I actually fixed this issue or if it is solved because of new data. Closing anyway.
