### ISSUE TITLE
Missing prefix "cbd_2014_pathway:" in pathway info of two datasets

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/unified-checklist#69]
I found that the pathway info linked to types `"introduction pathway"` (Checklist of alien herpetofauna of Belgium) and `"pathway of introduction"` (Checklist of alien species in the Scheldt estuary in Flanders, Belgium) discussed in #68 is not standardized as it doesn't start with the typical `cbd_2014_pathway:` prefix. @peterdesmet: I suppose this should be improved at checklist level as for #68, right?

Here a table of the values I found in `description`:

```r
suspect_type_pathways <- c(
  "introduction pathway",
  "pathway of introduction"
)

description %>% 
  filter(type %in% suspect_type_pathways) %>% 
  distinct(type, description) %>%
  arrange(type, description)
# A tibble: 19 x 2
   type                    description                  
   <chr>                   <chr>                        
 1 introduction pathway    contaminant                  
 2 introduction pathway    contaminant_timber           
 3 introduction pathway    escape_pet                   
 4 introduction pathway    escape_research              
 5 introduction pathway    nursery                      
 6 introduction pathway    release_conservation         
 7 introduction pathway    release_landscape_improvement
 8 introduction pathway    release_other                
 9 introduction pathway    stowaway_container           
10 introduction pathway    stowaway_other               
11 pathway of introduction contaminant_plant            
12 pathway of introduction corridor_water               
13 pathway of introduction escape_aquaculture           
14 pathway of introduction escape_pet                   
15 pathway of introduction release_fishery              
16 pathway of introduction stowaway                     
17 pathway of introduction stowaway_ballast_water       
18 pathway of introduction stowaway_hull_fouling        
19 pathway of introduction stowaway_ship                
```

**Comment by peterdesmet** [comment]
Ideally this is fixed at the checklist level, yes. ping @LienReyserhove. If needed urgently, I suggest to process this on your side, rather than we bake it in the unified processing...

**Comment by damianooldoni** [comment]
On short term, I agree with you, I will write a patch in the preprocessing workflow for indicators. Of course, this should be solved at checklist level to maintain the high level of standardization, typical of the unified checklist.

**Comment by LienReyserhove** [comment]
Done for alien scheldt checklist (see [this PR](https://github.com/trias-project/alien-scheldt-checklist/pull/10)), will do soon for herpetofauna

**Comment by LienReyserhove** [comment]
Done for herpetofauna, see https://github.com/trias-project/alien-herpetofauna-belgium/pull/18

**Comment by sangovae** [comment]
I am reviewing an old PR #10 that has not been merged yet. Is this issue

> Done for alien scheldt checklist (see [this PR](https://github.com/trias-project/alien-scheldt-checklist/pull/10)), will do soon for herpetofauna

I am reviewing this PR, since it is sill open.
Is this "cbd_2014_pathway:" still necessary, @damianooldoni ?

**Comment by LienReyserhove** [comment]
correct, this is solved with the new dwc term `pathway`, this should not be an issue anymore
