### ISSUE TITLE
`progress_estimated()` is deprecated

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#72]
> Warning: `progress_estimated()` was deprecated in dplyr 1.0.0.

Progress bars are still shown though, but I assume a separate package should be loaded?

**Comment by PietrH** [comment]
I suggest we use the built in progress bars in purrr instead: https://purrr.tidyverse.org/reference/progress_bars.html

**Comment by peterdesmet** [comment]
@PietrH I believe this is resolved as part of #83 and that this issue can be closed?

**Comment by PietrH** [comment]
Indeed
