### ISSUE TITLE
Higher taxa in checklist

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#84]
The following taxa make it into the final checklist as genus or higher. It would be good to verify those are correct (and we're not incorrectly labelling whole genera as exotic):

verificationKey | scientificName | kingdom | status | remark
--- | --- | --- | --- | ---
8782549 | Anolis Daudin, 1802 | Animalia | genus in sources (2) | ok
2442664 | Apalone Rafinesque, 1832 | Animalia | genus in source (2) | ok
2473221 | Blanus Wagler, 1830 | Animalia | genus in source | ok
2444141 | Boa Linnaeus, 1758 | Animalia | genus in source | ok
2453882 | Boaedon A.M.C.Duméril, Bibron & A.H.A.Duméril, 1854 | Animalia | genus in source | ok
2466496 | Calotes Cuvier, 1817 | Animalia | genus in source | ok
2161467 | Cerbalus Simon, 1897 | Animalia | genus in source | ok
5666 | Gekkonidae | Animalia | infraorder Gekkota in source (2) | ok (family is lower)
5221394 | Hemidactylus Oken, 1817 | Animalia | genus in source | ok
2459675 | Iguana Laurenti, 1768 | Animalia | genus in source | ok
3266899 | Lampropeltis Öpik, 1967 | Animalia | genus in source | ok
4553469 | Leiobunum Koch, 1839 | Animalia | genus in source | problematic
2284443 | Mastophorus Diesing, 1853 | Animalia | genus in source | ok
2443339 | Mauremys Gray, 1869 | Animalia | genus Mauremys (Gray, 1869) in source | ok
9245902 | Mauremys Ritgen, 1828 | Animalia | genus Mauremys (Gray, 1869) in source | changed to 2443339
7652364 | Nephila Leach, 1815 | Animalia | genus in source | ok
2161911 | Nolavia Kammerer, 2006 | Animalia | genus in source | ok
2162003 | Olios (Walckenaer, 1806) | Animalia | genus in source | problematic
2445496 | Pachydactylus Wiegmann, 1834 | Animalia | genus in source | ok
2447418 | Phelsuma Gray, 1825 | Animalia | genus in source | ok
2176168 | Phidippus C.L.Koch, 1846 | Animalia | genus in source | ok
2149911 | Pholcus Walckenaer, 1805 | Animalia | genus in source | problematic
2465626 | Pogona Storr, 1982 | Animalia | genus in source | ok
2454645 | Python Daudin, 1803 | Animalia | genus in source | ok
2457378 | Rhamphiophis Peters, 1854 | Animalia | genus in source | ok
2444221 | Sistrurus Garman, 1884 | Animalia | genus in source | ok
2202786 | Synarmadillo Dollfus, 1892 | Animalia | genus in source | ok
2441658 | Testudo Linnaeus, 1758 | Animalia | genus in source | ok
2457825 | Thamnophis Fitzinger, 1843 | Animalia | genus in source | ok
2513550 | Uromyces (Link) Unger, 1833 | Fungi | Uromyces proëminens (DC.) Pass. in Rabenh. in source | changed to 7239389
3092125 | Acmella Rich., 1807 | Plantae | genus in source | ok
3033893 | Berberis L. | Plantae | Berberis bealei Fortune (incl. hybrids) in source | changed to 3033888
3033893 | Berberis L. | Plantae | Berberis x wagneri (Jouin) Rehder in source | changed to 3982284
2771094 | Hosta | Plantae | genus in source | ok
3054376 | Pterocarya Kunth | Plantae | Pterocarya x rhederiana C.K. Schneider in source | changed to 4205304
8395064 | Rosa L. | Plantae | Rosa 'Dorothy Perkins' in source | changed: not mapped
8395064 | Rosa L. | Plantae | Rosa 'Hollandica' | changed to 3003979 (Rosa rugosa)
2705965 | Secale L. | Plantae | Secale xderzhavinii Tzvelev in source | changed to 4121360

**Comment by timadriaens** [comment]
There are natives in the following genera:

- Leiobunum
- Olios
- Pholcus
- Uromyces
- Berberis (but only one species, Berberis vulgaris, so the 2 in the table are alien)
- Rosa

**Comment by peterdesmet** [comment]
Uromyces, Berberis and Rosa will no longer appear (they have been fixed in the verification). The first three however appear on the source checklists, map fine and don't end up in the verification list. Should we explicitly remove those?

**Comment by timadriaens** [comment]
There could be specific issues, like "Leiobunum spA" which is essentially a still undescribed Leiobunum species that is alien to Belgium (and Europe). But the other genera I would remove. most of the information relevant to the workflows is at species level, so only kinda makes sense to keep the genera that are entirely alien to Belgium. Of course, experts mean to say "a species of the genus xxx alien to Belgium".

**Comment by peterdesmet** [comment]
@qgroom Pterocarya x rhederiana is now mapped to [Pterocarya ×rehderiana C.K.Schneid.](https://www.gbif.org/species/4205304), Berberis x wagneri to [Mahonia ×wagneri (Jouin) Rehder](https://www.gbif.org/species/3982284) (the accepted name for [Berberis ×wagneri Koehne
](https://www.gbif.org/species/3981541).

@timadriaens Olios and Pholcus are now explicitly removed in c9da1c9 and will be excluded in next publication.
