### ISSUE TITLE
What to do with stale branch get-taxa-verify-synonyms

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/unified-checklist#9]
@damianooldoni can you check if we can delete the branch `get-taxa-verify-synonyms`? Here is how it compares to master: https://github.com/trias-project/unified-checklist/compare/master...get-taxa-verify-synonyms

But most changes are maybe included in the newer https://github.com/trias-project/unified-checklist/tree/get_taxa_populate_spreadsheet

**Comment by damianooldoni** [comment]
Branch deleted.
